import globals from 'globals';

export default {
  configs: {
    core: {
      name: 'custom-js/core',
      rules: {
        // possible problems
        'array-callback-return': 2,
        'constructor-super': 2,
        'for-direction': 2,
        'getter-return': 2,
        'no-async-promise-executor': 2,
        'no-await-in-loop': 2,
        'no-class-assign': 2,
        'no-compare-neg-zero': 2,
        'no-cond-assign': [2, 'always'],
        'no-const-assign': 2,
        'no-constant-binary-expression': 2,
        'no-constant-condition': [2, { checkLoops: 'all' }],
        'no-constructor-return': 2,
        'no-control-regex': 2,
        'no-debugger': 2,
        'no-dupe-args': 2,
        'no-dupe-class-members': 2,
        'no-dupe-else-if': 2,
        'no-dupe-keys': 2,
        'no-duplicate-case': 2,
        'no-duplicate-imports': 2,
        'no-empty-character-class': 2,
        'no-empty-pattern': 2,
        'no-ex-assign': 2,
        'no-fallthrough': [
          2,
          { allowEmptyCase: true, reportUnusedFallthroughComment: true },
        ],
        'no-func-assign': 2,
        'no-import-assign': 2,
        'no-inner-declarations': 0,
        'no-invalid-regexp': 2,
        'no-irregular-whitespace': 2,
        'no-loss-of-precision': 2,
        'no-misleading-character-class': 2,
        'no-new-native-nonconstructor': 2,
        'no-obj-calls': 2,
        'no-promise-executor-return': [2, { allowVoid: true }],
        'no-prototype-builtins': 2,
        'no-self-assign': 2,
        'no-self-compare': 2,
        'no-setter-return': 2,
        'no-sparse-arrays': 2,
        'no-template-curly-in-string': 2,
        'no-this-before-super': 2,
        'no-unassigned-vars': 2,
        'no-undef': [2, { typeof: false }],
        'no-unexpected-multiline': 0,
        'no-unmodified-loop-condition': 2,
        'no-unreachable': 2,
        'no-unreachable-loop': 2,
        'no-unsafe-finally': 2,
        'no-unsafe-negation': [2, { enforceForOrderingRelations: true }],
        'no-unsafe-optional-chaining': [
          2,
          { disallowArithmeticOperators: true },
        ],
        'no-unused-private-class-members': 2,
        'no-unused-vars': [
          2,
          {
            vars: 'all',
            args: 'all',
            caughtErrors: 'all',
            varsIgnorePattern: '^_',
            argsIgnorePattern: '^_',
            destructuredArrayIgnorePattern: '^_',
            ignoreRestSiblings: false,
            ignoreClassWithStaticInitBlock: false,
            reportUsedIgnorePattern: true,
          },
        ],
        'no-use-before-define': [
          2,
          {
            functions: true,
            classes: true,
            variables: true,
            allowNamedExports: false,
            enums: true,
            typedefs: true,
            ignoreTypeReferences: false,
          },
        ],
        'no-useless-assignment': 2,
        'no-useless-backreference': 2,
        'require-atomic-updates': 2,
        'use-isnan': 2,
        'valid-typeof': [2, { requireStringLiterals: true }],

        // suggestions
        'accessor-pairs': 2,
        'arrow-body-style': [2, 'as-needed'],
        'block-scoped-var': 2,
        'camelcase': 2,
        'capitalized-comments': [2, 'never'],
        'class-methods-use-this': [2, { ignoreOverrideMethods: true }],
        'complexity': 0,
        'consistent-return': 2,
        'consistent-this': [2, 'self'],
        'curly': [2, 'all'],
        'default-case': 2,
        'default-case-last': 2,
        'dot-notation': 2,
        'eqeqeq': 2,
        'func-name-matching': 2,
        'func-names': [2, 'as-needed'],
        'func-style': [2, 'expression'],
        'grouped-accessor-pairs': [2, 'getBeforeSet'],
        'guard-for-in': 2,
        'id-denylist': 0,
        'id-length': 0,
        'id-match': 0,
        'init-declarations': 0,
        'logical-assignment-operators': [
          2,
          'always',
          { enforceForIfStatements: true },
        ],
        'max-classes-per-file': [2, 1],
        'max-depth': [2, 4],
        'max-lines': [2, 300],
        'max-lines-per-function': [
          2,
          { max: 50, skipBlankLines: true, skipComments: true, IIFEs: true },
        ],
        'max-nested-callbacks': [2, 3],
        'max-params': [2, 3],
        'max-statements': 0,
        'new-cap': [2, { properties: true }],
        'no-alert': 2,
        'no-array-constructor': 2,
        'no-bitwise': 2,
        'no-caller': 2,
        'no-case-declarations': 2,
        'no-console': 2,
        'no-continue': 2,
        'no-delete-var': 2,
        'no-div-regex': 2,
        'no-else-return': [2, { allowElseIf: false }],
        'no-empty': [2, { allowEmptyCatch: true }],
        'no-empty-function': 2,
        'no-empty-static-block': 2,
        'no-eq-null': 0,
        'no-eval': 2,
        'no-extend-native': 2,
        'no-extra-bind': 2,
        'no-extra-boolean-cast': [2, { enforceForInnerExpressions: true }],
        'no-extra-label': 2,
        'no-global-assign': 2,
        'no-implicit-coercion': [
          2,
          {
            boolean: true,
            number: true,
            string: true,
            disallowTemplateShorthand: true,
          },
        ],
        'no-implicit-globals': [2, { lexicalBindings: true }],
        'no-implied-eval': 2,
        'no-inline-comments': 0,
        'no-invalid-this': [2, { capIsConstructor: false }],
        'no-iterator': 2,
        'no-label-var': 2,
        'no-labels': 0,
        'no-lone-blocks': 2,
        'no-lonely-if': 2,
        'no-loop-func': 2,
        'no-magic-numbers': 2,
        'no-multi-assign': 2,
        'no-multi-str': 2,
        'no-negated-condition': 2,
        'no-nested-ternary': 0,
        'no-new': 2,
        'no-new-func': 2,
        'no-new-wrappers': 2,
        'no-nonoctal-decimal-escape': 2,
        'no-object-constructor': 2,
        'no-octal': 2,
        'no-octal-escape': 2,
        'no-param-reassign': [2, { props: true }],
        'no-plusplus': 0,
        'no-proto': 2,
        'no-redeclare': 2,
        'no-regex-spaces': 2,
        'no-restricted-exports': 0,
        'no-restricted-globals': [2, 'event'],
        'no-restricted-imports': 0,
        'no-restricted-properties': 0,
        'no-restricted-syntax': [2, 'FunctionExpression', 'SequenceExpression'],
        'no-return-assign': [2, 'always'],
        'no-script-url': 2,
        'no-sequences': 0,
        'no-shadow': 2,
        'no-shadow-restricted-names': [2, { reportGlobalThis: true }],
        'no-ternary': 0,
        'no-throw-literal': 2,
        'no-undef-init': 0,
        'no-undefined': 0,
        'no-underscore-dangle': 0,
        'no-unneeded-ternary': [2, { defaultAssignment: false }],
        'no-unused-expressions': 2,
        'no-unused-labels': 2,
        'no-useless-call': 2,
        'no-useless-catch': 2,
        'no-useless-computed-key': 0,
        'no-useless-concat': 0,
        'no-useless-constructor': 2,
        'no-useless-escape': 2,
        'no-useless-rename': 0,
        'no-useless-return': 2,
        'no-var': 2,
        'no-void': 2,
        'no-warning-comments': [2, { terms: ['TODO'], location: 'anywhere' }],
        'no-with': 2,
        'object-shorthand': 0,
        'one-var': 0,
        'operator-assignment': 0,
        'prefer-arrow-callback': 0,
        'prefer-const': 2,
        'prefer-destructuring': 0,
        'prefer-exponentiation-operator': 2,
        'prefer-named-capture-group': 0,
        'prefer-numeric-literals': 0,
        'prefer-object-has-own': 0,
        'prefer-object-spread': 2,
        'prefer-promise-reject-errors': 2,
        'prefer-regex-literals': 0,
        'prefer-rest-params': 2,
        'prefer-spread': 0,
        'prefer-template': 0,
        'radix': 0,
        'require-await': 2,
        'require-unicode-regexp': 0,
        'require-yield': 2,
        'sort-imports': [
          2,
          {
            memberSyntaxSortOrder: ['none', 'multiple', 'single', 'all'],
            allowSeparatedGroups: true,
          },
        ],
        'sort-keys': 0,
        'sort-vars': 0,
        'strict': 0,
        'symbol-description': 2,
        'vars-on-top': 0,
        'yoda': 2,

        // layout & formatting
        'unicode-bom': 0,
      },
    },
    linterOptionsDefault: {
      name: 'custom-js/linterOptionsDefault',
      linterOptions: {
        noInlineConfig: false,
        reportUnusedDisableDirectives: 'error',
        reportUnusedInlineConfigs: 'error',
      },
    },
    languageOptionsDefault: {
      name: 'custom-js/languageOptionsDefault',
      languageOptions: {
        globals: globals.browser,
      },
    },
  },
};
